# **Welcome to the MRInference machine learning tutorial!**
by Sandra Vieira

---
This webpage contains a brief step-by-step tutorial on the implementation of a standard supervised machine learning pipeline using Python programming language. Before this tutorial make sure to go through the pre-recorded lectures:  

*   Introduction to Machine Learning
*   The Machine Learning Pipeline 


---
##Machine Learning: Methods and Applications to Brain Disorders
This tutorial and both pre-recorded lectures above are based on the book [Machine Learning: Methods and Applications to Brain Disorders](https://www.amazon.co.uk/Machine-Learning-Methods-Applications-Disorders/dp/0128157399). The pre-recorded lectures are based on chapters 1-3 and this tutorial is a shorter version of Chapter 19. You can access the full tutorial of Chapter 19 [here](https://github.com/MLMH-Lab/How-To-Build-A-Machine-Learning-Model).

---  
## Aim and structure of the tutorial
For this tutorial you will use a toy dataset containing the grey matter volume and thickness from different brain regions extracted with FreeSurfer to classify patients with schizophrenia and healthy controls using a Support Vector Machine (SVM). The main steps of the tutrial will follow the pipeline presented in lecture The Machine Learning Pipeline and are shown in the figure below.

![workflow](https://raw.githubusercontent.com/MLMH-Lab/How-To-Build-A-Machine-Learning-Model/master/figures/Figure%201.png)



## Importing libraries

Python language is organised in libraries. Each library contains a set of functions for a specific purpose. For example, numpy is a popular library for manipulating numerical data, while pandas is most commonly used to handle tabular data. There are several libraries for machine learning analysis; in this tutorial we will use scikitlearn. 

In [ ]:
# SNIPPET 1

# Manipulate data
import numpy as np
import pandas as pd

# Plots
import seaborn as sns
import matplotlib.pyplot as plt

# Statistical tests
import scipy.stats as stats

# Machine learning
from sklearn.svm import LinearSVC
from sklearn.externals import joblib
from sklearn.metrics import balanced_accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, GridSearchCV

# Ignore WARNING
import warnings

warnings.filterwarnings('ignore')

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


Some steps in our analysis will be subjected to randomness.  We should set the  seed value to a fixed number to guarantee that we get the same results every time we run the code. 

In [ ]:
# SNIPPET 2
random_seed = 1
np.random.seed(random_seed)

## Problem formulation

 In this tutorial, our machine learning problem is: 

> *Classify patients with schizophrenia and healthy controls using structural MRI data.*

From this formulation we can derive the main elements of our machine learning problem:

*   **Features**: Structural MRI data
*   **Task**: Binary classification
*   **Target**: Patients with schizophrenia and healthy controls



---



## Data Preparation

The aim of this step is to perform a series of statistical analyses to get the data ready for the machine learning model. In this tutorial, we will assume the data is ready to be analysed. However, in a real project we would want to pay close attention to several things including class imbalance (N HC vs N SZ), missing data (data imputation?), confounding variables (age, sex?), dimensionality (N features vs N participants).

### Loading the data

In [ ]:
# SNIPPET 4
# dataset_file = Path('./Chapter_19_data.csv')
dataste_url = 'https://raw.githubusercontent.com/sandramv/MRInference_ML_Tutorial/main/ml_tutorial_data.csv'
dataset_df = pd.read_csv(dataste_url, index_col='ID')

In [ ]:
# SNIPPET 6
dataset_df[0:6]

Diagnosis  ...  rh insula thickness
ID              ...                     
c001        hc  ...             2.645844
c002        hc  ...             2.673699
c003        hc  ...             2.795989
c004        hc  ...             2.731654
c005        hc  ...             2.607771
c006        hc  ...             2.606643

[6 rows x 170 columns]

In [ ]:
# SNIPPET 8
print('Number of features = %d' % dataset_df.shape[1])
print('Number of participants = %d' % dataset_df.shape[0])

Number of features = 170
Number of participants = 740


In [ ]:
# SNIPPET 11
dataset_df['Diagnosis'].value_counts()

sz    372
hc    368
Name: Diagnosis, dtype: int64

### Feature set and target

Our next step is to retrieve the target and features from the dataset.

In [ ]:
# SNIPPET 17
# Target
targets_df = dataset_df['Diagnosis']

# Features
features_names = dataset_df.columns[1:]
features_df = dataset_df[features_names]

In [ ]:
# SNIPPET 17a
features_df

Left Lateral Ventricle  ...  rh insula thickness
ID                            ...                     
c001             4226.907844  ...             2.645844
c002             4954.912699  ...             2.673699
c003             4470.611989  ...             2.795989
c004             7553.310654  ...             2.731654
c005             8785.212771  ...             2.607771
...                      ...  ...                  ...
p368             8283.573193  ...             2.913156
p369             5507.374607  ...             2.892605
p370             3607.623866  ...             3.066604
p371             8276.575805  ...             2.631420
p372             5170.559424  ...             3.330186

[740 rows x 169 columns]

In [ ]:
# SNIPPET 19
targets_df = targets_df.map({'hc': 0, 'sz': 1})
targets = targets_df.values.astype('int')

features = features_df.values.astype('float32')

## Feature engineering


### Feature extraction
In our example, we want to use neuroanatomical data to classify SZ and HC. This requires the extraction of brain morphometric information from the raw MRI images.


### Feature scaling/normalization 
In brain disorders research, we often deal with datasets that contain features that vary in units and range. However, to model the data correctly and effectively, most machine learning algorithms require the data to be on the same scale. Since normalization involves statistics (e.g. mean and variance) of the set used to train the model, in this point we split the data into training and test sets following the scheme a cross-validation.

In [ ]:
# SNIPPET 20
n_folds = 10
skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=random_seed)

![alt text](https://raw.githubusercontent.com/MLMH-Lab/How-To-Build-A-Machine-Learning-Model/master/figures/Figure%202.png)

In [ ]:
# SNIPPET 21
predictions_df = pd.DataFrame(targets_df)
predictions_df['predictions'] = np.nan

bac_cv = np.zeros((n_folds, 1))
sens_cv = np.zeros((n_folds, 1))
spec_cv = np.zeros((n_folds, 1))
coef_cv = np.zeros((n_folds, len(features_names)))

In [ ]:
# SNIPPET 22 REDO WITHOUT CV?!
for i_fold, (train_idx, test_idx) in enumerate(skf.split(features, targets)):
    features_train, features_test = features[train_idx], features[test_idx]
    targets_train, targets_test = targets[train_idx], targets[test_idx]

    print('CV iteration: %d' % (i_fold + 1))
    print('Training set size: %d' % len(targets_train))
    print('Test set size: %d' % len(targets_test))

    # --------------------------------------------------------------------------
    # SNIPPET 23
    # Feature scaling/normalization
    scaler = StandardScaler()

    scaler.fit(features_train)

    features_train_norm = scaler.transform(features_train)
    features_test_norm = scaler.transform(features_test)

    # --------------------------------------------------------------------------
    # SNIPPET 24
    # Here, we will use the linear kernel, as this will make it easier to extract the coefficients
    #  of the SVM model (feature importance) later on.
    clf = LinearSVC(loss='hinge')

    # --------------------------------------------------------------------------
    # SNIPPET 25
    # SVM relies on a hyperparameter C that regulates how much we want to avoid misclassifying each
    #  training example.

    # Hyper-parameter search space
    param_grid = {'C': [2 ** -6, 2 ** -5, 2 ** -4, 2 ** -3, 2 ** -2, 2 ** -1, 2 ** 0, 2 ** 1]}

    # Grid search
    internal_cv = StratifiedKFold(n_splits=10)
    grid_cv = GridSearchCV(estimator=clf,
                           param_grid=param_grid,
                           cv=internal_cv,
                           scoring='balanced_accuracy',
                           verbose=1)

    # --------------------------------------------------------------------------
    # SNIPPET 26
    # Model training
    grid_result = grid_cv.fit(features_train_norm, targets_train)

    # --------------------------------------------------------------------------
    # SNIPPET 27
    print('Best: %f using %s' % (grid_result.best_score_, grid_result.best_params_))
    means = grid_result.cv_results_['mean_test_score']
    stds = grid_result.cv_results_['std_test_score']
    params = grid_result.cv_results_['params']

    for mean, stdev, param in zip(means, stds, params):
        print('%f (%f) with: %r' % (mean, stdev, param))

    # --------------------------------------------------------------------------
    # SNIPPET 28
    best_clf = grid_cv.best_estimator_

    # --------------------------------------------------------------------------
    # SNIPPET 30
    # Model evaluation
    # Finally, we use the final trained model best_clf to make predictions in the test set.
    target_test_predicted = best_clf.predict(features_test_norm)

    # --------------------------------------------------------------------------
    # SNIPPET 31
    print('Confusion matrix')
    cm = confusion_matrix(targets_test, target_test_predicted)
    print(cm)

    tn, fp, fn, tp = cm.ravel()

    bac_test = balanced_accuracy_score(targets_test, target_test_predicted)
    sens_test = tp / (tp + fn)
    spec_test = tn / (tn + fp)

    print('Balanced accuracy: %.3f ' % bac_test)
    print('Sensitivity: %.3f ' % sens_test)
    print('Specificity: %.3f ' % spec_test)

    bac_cv[i_fold, :] = bac_test
    sens_cv[i_fold, :] = sens_test
    spec_cv[i_fold, :] = spec_test
    print('--------------------------------------------------------------------------')

CV iteration: 1
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.681996 using {'C': 0.03125}
0.656239 (0.082053) with: {'C': 0.015625}
0.681996 (0.084610) with: {'C': 0.03125}
0.672950 (0.086047) with: {'C': 0.0625}
0.681863 (0.084353) with: {'C': 0.125}
0.660561 (0.069703) with: {'C': 0.25}
0.663592 (0.070552) with: {'C': 0.5}
0.660517 (0.063467) with: {'C': 1}
0.650000 (0.070569) with: {'C': 2}
Confusion matrix
[[29  8]
 [13 24]]
Balanced accuracy: 0.716 
Sensitivity: 0.649 
Specificity: 0.784 
--------------------------------------------------------------------------
CV iteration: 2
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.684537 using {'C': 0.25}
0.657442 (0.060636) with: {'C': 0.015625}
0.675535 (0.071928) with: {'C': 0.03125}
0.683200 (0.069288) with: {'C': 0.0625}
0.683066 (0.061052) with: {'C': 0.125}
0.684537 (0.068300) with: {'C': 0.25}
0.678565 (0.069170) with: {'C': 0.5}
0.655971 (0.067399) with: {'C': 1}
0.650089 (0.080730) with: {'C': 2}
Confusion matrix
[[27 10]
 [10 27]]
Balanced accuracy: 0.730 
Sensitivity: 0.730 
Specificity: 0.730 
--------------------------------------------------------------------------
CV iteration: 3
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.678565 using {'C': 0.25}
0.671257 (0.083172) with: {'C': 0.015625}
0.657843 (0.090354) with: {'C': 0.03125}
0.672504 (0.071297) with: {'C': 0.0625}
0.675579 (0.085828) with: {'C': 0.125}
0.678565 (0.096041) with: {'C': 0.25}
0.675535 (0.100533) with: {'C': 0.5}
0.656105 (0.095358) with: {'C': 1}
0.656283 (0.092216) with: {'C': 2}
Confusion matrix
[[26 11]
 [12 25]]
Balanced accuracy: 0.689 
Sensitivity: 0.676 
Specificity: 0.703 
--------------------------------------------------------------------------
CV iteration: 4
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.677050 using {'C': 0.125}
0.666667 (0.087044) with: {'C': 0.015625}
0.659091 (0.086701) with: {'C': 0.03125}
0.672549 (0.076349) with: {'C': 0.0625}
0.677050 (0.074486) with: {'C': 0.125}
0.665152 (0.066903) with: {'C': 0.25}
0.648574 (0.062914) with: {'C': 0.5}
0.657665 (0.074417) with: {'C': 1}
0.663681 (0.085317) with: {'C': 2}
Confusion matrix
[[23 14]
 [ 6 31]]
Balanced accuracy: 0.730 
Sensitivity: 0.838 
Specificity: 0.622 
--------------------------------------------------------------------------
CV iteration: 5
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.660829 using {'C': 0.125}
0.654768 (0.066926) with: {'C': 0.015625}
0.645766 (0.077823) with: {'C': 0.03125}
0.639840 (0.074877) with: {'C': 0.0625}
0.660829 (0.072983) with: {'C': 0.125}
0.651738 (0.076762) with: {'C': 0.25}
0.635294 (0.085356) with: {'C': 0.5}
0.632308 (0.097250) with: {'C': 1}
0.636809 (0.080568) with: {'C': 2}
Confusion matrix
[[22 15]
 [ 3 34]]
Balanced accuracy: 0.757 
Sensitivity: 0.919 
Specificity: 0.595 
--------------------------------------------------------------------------
CV iteration: 6
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.651337 using {'C': 0.125}
0.615553 (0.087564) with: {'C': 0.015625}
0.622995 (0.085502) with: {'C': 0.03125}
0.634804 (0.080206) with: {'C': 0.0625}
0.651337 (0.075556) with: {'C': 0.125}
0.633422 (0.063303) with: {'C': 0.25}
0.623039 (0.082717) with: {'C': 0.5}
0.630704 (0.073362) with: {'C': 1}
0.644430 (0.074283) with: {'C': 2}
Confusion matrix
[[31  6]
 [ 8 29]]
Balanced accuracy: 0.811 
Sensitivity: 0.784 
Specificity: 0.838 
--------------------------------------------------------------------------
CV iteration: 7
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.665152 using {'C': 0.125}
0.662166 (0.086544) with: {'C': 0.015625}
0.659046 (0.087600) with: {'C': 0.03125}
0.657487 (0.074425) with: {'C': 0.0625}
0.665152 (0.077787) with: {'C': 0.125}
0.653075 (0.056146) with: {'C': 0.25}
0.634848 (0.078374) with: {'C': 0.5}
0.622772 (0.076761) with: {'C': 1}
0.630348 (0.072909) with: {'C': 2}
Confusion matrix
[[29  8]
 [11 26]]
Balanced accuracy: 0.743 
Sensitivity: 0.703 
Specificity: 0.784 
--------------------------------------------------------------------------
CV iteration: 8
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.672906 using {'C': 0.03125}
0.659492 (0.097342) with: {'C': 0.015625}
0.672906 (0.087826) with: {'C': 0.03125}
0.662389 (0.078545) with: {'C': 0.0625}
0.666934 (0.089875) with: {'C': 0.125}
0.657888 (0.086627) with: {'C': 0.25}
0.653298 (0.080025) with: {'C': 0.5}
0.654813 (0.077727) with: {'C': 1}
0.645900 (0.069074) with: {'C': 2}
Confusion matrix
[[30  7]
 [10 27]]
Balanced accuracy: 0.770 
Sensitivity: 0.730 
Specificity: 0.811 
--------------------------------------------------------------------------
CV iteration: 9
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Best: 0.672193 using {'C': 0.0625}
0.648128 (0.076796) with: {'C': 0.015625}
0.652674 (0.078949) with: {'C': 0.03125}
0.672193 (0.068385) with: {'C': 0.0625}
0.651471 (0.077171) with: {'C': 0.125}
0.658913 (0.077373) with: {'C': 0.25}
0.640686 (0.073699) with: {'C': 0.5}
0.640686 (0.085128) with: {'C': 1}
0.642291 (0.081810) with: {'C': 2}
Confusion matrix
[[26 10]
 [ 9 29]]
Balanced accuracy: 0.743 
Sensitivity: 0.763 
Specificity: 0.722 
--------------------------------------------------------------------------
CV iteration: 10
Training set size: 666
Test set size: 74
Fitting 10 folds for each of 8 candidates, totalling 80 fits
Best: 0.681684 using {'C': 0.125}
0.661943 (0.088166) with: {'C': 0.015625}
0.664929 (0.102367) with: {'C': 0.03125}
0.676961 (0.082928) with: {'C': 0.0625}
0.681684 (0.070080) with: {'C': 0.125}
0.678788 (0.071619) with: {'C': 0.25}
0.660695 (0.059294) with: {'C': 0.5}
0.653119 (0.067356) with: {'C': 1}
0.657754 (0.081060) with: {'C': 2}
Confusion matrix
[[28

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    7.2s finished


In [ ]:
# SNIPPET 32
print('CV results')
print('Bac: Mean(SD) = %.3f(%.3f)' % (bac_cv.mean(), bac_cv.std()))
print('Sens: Mean(SD) = %.3f(%.3f)' % (sens_cv.mean(), sens_cv.std()))
print('Spec: Mean(SD) = %.3f(%.3f)' % (spec_cv.mean(), spec_cv.std()))

CV results
Bac: Mean(SD) = 0.737(0.036)
Sens: Mean(SD) = 0.737(0.092)
Spec: Mean(SD) = 0.736(0.075)


## Post-hoc analysis

Once we have our final model, we can run several additional analyses. This tutotial does not include these analysis, but we could look at the following:

*   Test balanced accuracy, sensitivity and specificity for statistical significance via permutation testing
*   Identify the features that provided the greatest contribution to the task 